routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\RoleController;
use App\Models\Game;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//登入
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//HOT和全部列表
Route::get('/',[GameController::class,'index'])->name('root');
Route::get('/all',[GameController::class,'index_all'])->name('all');
Route::resource('games',GameController::class);//編輯 刪除..等等

//留言
Route::post('/games/{gameId}/comments', [CommentController::class, 'store'])->name('comments.store');
Route::delete('games/{gameId}/comments/{comment}', [CommentController::class, 'destroy'])->name('comments.destroy');

//搜尋欄
Route::get('/search', [GameController::class,'search'])->name('search');

//權限控制頁面
Route::get('/role_control', [RoleController::class,'index'])->name('controll')->middleware('can:admin');

// 更新成 ROLE_ADMIN
Route::put('/users/{user}/set-admin', [RoleController::class,'setAdmin'])->name('users.set_admin');

// 更新用户角色为ROLE_MANAGER
Route::put('/users/{user}/set-manager', [RoleController::class,'setManager'])->name('users.set_manager');

// 更新用户角色为ROLE_USER
Route::put('/users/{user}/set-user', [RoleController::class,'setUser'])->name('users.set_user');

//購物車
Route::get('/shoplist',[GameController::class,'shoplist'])->name('shoplist');
Route::post('/games/{gameId}/add-to-cart', [GameController::class,'addToCart'])->name('games.addToCart');//加入購物車
Route::post('/shoplist/clean', [GameController::class,'cleanShoplist'])->name('shoplist.clean');//清除購物車
Route::delete('/shoplist/{id}', [GameController::class,'destroyShoplist'])->name('shoplist.destroy');
Route::post('/shoplist/buy', [GameController::class,'buyFromShoplist'])->name('shoplist.buy');

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;
    public function user(){
        return $this->belongsTo('App\Models\User');
    }
    public function comments(){
        return $this->hasMany('App\Models\Comment');
    }    
    
    protected $fillable=['title','tag','content','price','image'];
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Game;
use Illuminate\Support\Facades\Storage;

class GameController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware(('auth'))->except(['index', 'show', 'search', 'index_all']);
    }
    public function index()
    {
        $games = Game::withCount('comments')
            ->orderBy('comments_count', 'desc')
            ->paginate(5);

        return view('games.index', ['games' => $games]);
    }
    public function index_all(Request $request)
    {
        $sort = $request->input('sort');

        $query = Game::query();

        if ($sort === 'time') {
            // 按時間排序：最新的排在前面
            $query->orderByDesc('created_at');
        } elseif ($sort === 'timeReverse') {
            // 按留言數排序：按遊戲的留言數量排序
            $query->orderBy('created_at', 'asc');
        } elseif ($sort === 'price') {
            $query->orderByDesc('price');
        } elseif ($sort === 'priceReverse') {
            $query->orderBy('price', 'asc');
        }
        $games = $query->paginate(5);
        if ($sort === 'comments') {
            // 按留言數排序：按遊戲的留言數量排序
            $games = Game::withCount('comments')
                ->orderBy('comments_count', 'desc')
                ->paginate(5);
        } elseif ($sort === 'commentsReverse') {
            // 按留言數排序：按遊戲的留言數量排序
            $games = Game::withCount('comments')
                ->orderBy('comments_count', 'asc')
                ->paginate(5);
        }
        return view('games.index_all', ['games' => $games, 'sort' => $sort]);
    }
    public function create()
    {
        return view('games.create');
    }
    public function store(Request $request)
    {
        $content = $request->validate([
            'title' => 'required',
            'tag' => 'required',
            'price' => 'required',
            'content' => 'required|min:10',
            'image' => 'mimes:jpeg,jpg,png,gif|required|max:10000'
        ]);
        if ($request->hasFile('image')) {
            $imagePath = $request->file('image')->store('images', 'public');
            $content['image'] = $imagePath;
        }
        auth()->user()->games()->create($content);
        return redirect()->route('root')->with('notice', '遊戲新增成功!');
    }
    public function edit($id)
    {
        $games = Game::find($id);
        return view('games.edit', ['game' => $games]);
    }
    public function update(Request $request, $id)
    {
        $game = Game::find($id);
        $content = $request->validate([
            'title' => 'required',
            'tag' => 'required',
            'price' => 'required',
            'content' => 'required|min:10',
        ]);
        if ($request->hasFile('image')) {
            $request->validate([
                'image' => 'mimes:jpeg,jpg,png,gif|required|max:10000',
            ]);
            if ($game->image) {
                Storage::delete('public/' . $game->image);
            }
            // 保存新图片到 storage/app/public/images 目录
            $imagePath = $request->file('image')->store('images', 'public');
            $content['image'] = $imagePath;
        }
        $game->update($content);
        return redirect()->route('root')->with('notice', '遊戲內容更新成功');
    }
    public function show($id)
    {
        $game = Game::find($id);
        $totalComments = $game->comments()->count();
        $totalLikes = $game->comments()->where('like_type', 1)->count();
        $totalDislikes = $game->comments()->where('like_type', 2)->count();
        return view('games.show', [
            'game' => $game, 'totalComments' => $totalComments, 'totalLikes' => $totalLikes,
            'totalDislikes' => $totalDislikes,
        ]);
    }
    public function destroy($id)
    {
        $game = Game::find($id);
        foreach ($game->comments as $comment) {
            $comment->delete();
        }
        if ($game->image) {
            Storage::delete('public/' . $game->image);
        }
        $game->delete();
        return redirect()->route('root')->with('notice' . '遊戲已刪除');
    }

    public function search(Request $request)
    {
        // 取得搜尋關鍵字
        $keyword = $request->query('query');

        // 使用搜尋關鍵字進行遊戲標題的模糊搜尋
        $games = Game::where('title', 'like', '%' . $keyword . '%')->paginate(5);

        return view('games.search', ['games' => $games]);
    }
    public function shoplist()
    {
        $user = auth()->user();
        // 確認使用者是否存在購物車欄位，若不存在則初始化為空陣列
        if (!$user->shopping_cart) {
            $user->shopping_cart = [];
        }

        // 取得購物車內的遊戲 ID
        $gameIds = $user->shopping_cart;

        // 根據遊戲 ID 取得遊戲資料
        $games = Game::whereIn('id', $gameIds)->get();

        $totalAmount = $games->sum('price');


        // 將遊戲資料傳遞到 shoplist.blade.php 模板中
        return view('games.shoplist', ['games' => $games, 'totalAmount' => $totalAmount]);
    }
    public function addToCart($id)
    {
        // 取得當前登入的使用者
        $user = auth()->user();

        // 確認使用者是否存在購物車欄位，若不存在則初始化為空陣列
        if (!$user->shopping_cart) {
            $user->shopping_cart = [];
        }

        // 取得目前的購物車內容
        $shoppingCart = $user->shopping_cart;

        // 將遊戲 ID 加入購物車
        if (!in_array($id, $shoppingCart)) {
            // 遊戲 ID 不存在於購物車中，才將其加入
            $shoppingCart[] = $id;

            // 將修改後的購物車內容儲存回資料庫
            $user->shopping_cart = $shoppingCart;
            $user->save();

            return redirect()->back()->with('notice', '遊戲已新增到購物車！');
        } else {
            // 遊戲已存在於購物車中，直接返回並顯示提示訊息
            return redirect()->back()->with('notice', '遊戲已經在購物車中！');
        }
    }
    public function destroyShoplist($id){
        // 取得當前登入的使用者
        $user = auth()->user();

        // 在購物車內容中尋找要刪除的遊戲 ID 的索引
        $index = array_search($id, $user->shopping_cart);

        $shoppingCart = $user->shopping_cart;

        unset($shoppingCart[$index]);

            // 重新索引陣列，以避免留下空洞
        $user->shopping_cart = array_values($shoppingCart);

            // 將修改後的購物車內容儲存回資料庫
        $user->save();

        return redirect()->back()->with('notice', '遊戲已從購物車中移除！');
    }
    
    public function cleanShoplist(){
        $user = auth()->user();

        $user->shopping_cart = [];

        $user->save();

        return redirect()->back()->with('notice', '購物車已清空！');
    }
    public function buyFromShoplist(){
    // 取得當前登入的使用者
    $user = auth()->user();

    // 取得購物車內容
    $shoppingCart = $user->shopping_cart;
    
    
    $ownedGames = $user->owned_games;
    
    if (!$ownedGames) {
        $ownedGames = [];
    }
    // 將購物車內容複製到 owned_games 中
    $ownedGames = array_merge($ownedGames, $shoppingCart);

    $user->owned_games = array_values($ownedGames);
    // 清空購物車
    $user->shopping_cart = [];

    // 儲存修改後的使用者資料
    $user->save();

    return redirect()->route('shoplist')->with('notice', '購買成功！');
}
}

resources/views/games/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<h1 class="font-thin text-4xl">新增遊戲</h1>
@if($errors->any())
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{route('games.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="field my-2">
        <p style="font-size: 30px">主題<p>
        <input type="text" value="{{old('title')}}" name="title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" style="font-size: 20px"/>
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">標籤<p>
        <input type="text" value="{{old('tag')}}" name="tag" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" style="font-size: 20px"/>
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">圖片<p>
        <input type="file" name="image">
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">內文<p>
        <textarea name="content" cols="30" rows="10" class="form-control" id="exampleFormControlTextarea1" rows="3" style="font-size: 20px">{{old('content')}}</textarea>
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">價格<p>
        <input type="text" value="{{old('price')}}" name="price" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" style="font-size: 20px"/>
    </div>
    <div class="actions">
        <button type="submit" class="btn btn-primary btn-lg">新增遊戲</button>
    </div>
</form>
</div>
@endsection

resources/views/games/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<h1 class="font-thin text-4xl">編輯遊戲資訊</h1>
@if($errors->any())
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{route('games.update',$game)}}" method="post" enctype="multipart/form-data">
    @csrf
    @method('patch')
    <div class="field my-2">
        <p style="font-size: 30px">名稱<p>
        <input type="text" value="{{$game->title}}" name="title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" style="font-size: 20px"/>
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">標籤<p>
        <input type="text" value="{{$game->tag}}" name="tag" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" style="font-size: 20px"/>
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">當前圖片<p>
        <img src="{{ asset('storage/' . $game->image) }}" alt="遊戲圖片" class="img-fluid">
        <p style="font-size: 30px">更換圖片<p>
        <input type="file" name="image">
    </div>        
    <div class="field my-2">
        <p style="font-size: 30px">內文<p>
        <textarea name="content" cols="30" rows="10" class="form-control" id="exampleFormControlTextarea1" rows="3" style="font-size: 20px">{{$game->content}}</textarea>
    </div>
    <div class="field my-2">
        <p style="font-size: 30px">價格<p>
        <input type="text" value="{{$game->price}}" name="price" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" style="font-size: 20px"/>
    </div>
    <div class="actions">
        <button type="submit" class="btn btn-primary btn-lg">編輯完成</button>
    </div>
</form>
</div>
@endsection

resources/views/games/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex">
        <h1 class="me-auto">熱門TOP5</h1>
        @can('admin')
        <a href="{{ route('games.create') }}" style="font-size: 30px">新增遊戲</a>
        @elsecan('manager')
        <a href="{{ route('games.create') }}" style="font-size: 30px">新增遊戲</a>
        @endcan
        
    </div>
    <div class="list-group">
        @foreach($games as $game)
        <div class="qwer">
            <div class="list-group-item list-group-item-action m-1">
                <div class="d-flex justify-content-between ">
                    <!-- 標題 -->
                    <h2 class="font-bold text-lg" style="margin-bottom: 30px ">
                        <a href="{{route('games.show',$game)}}">{{$game->title}}</a>
                        <br>
                        <br>
                        <p style="font-size: 20px">#{{$game->tag}}</p>
                    </h2>
                    <!-- 圖片 -->
                    <div class="justify-content-end">
                        <img src="{{ asset('storage/' . $game->image) }}"  style="width: 200px;" alt="遊戲圖片">
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <!-- 價格和發行 -->
                    <p class="" style="font-size: 20px">
                        價格:{{$game->price}}
                    </p>
                    <p class="d-none d-md-block" style="font-size: 20px" >{{$game->created_at}} 由 {{$game->user->name}} 發行</p>
                </div>
            </div>
            @can('admin')
            <div class="d-flex justify-content-end">
                <a href="{{route('games.edit',['game'=>$game->id])}}" class="btn btn-outline-primary" style="margin-right:10px ">編輯</a>
                <form action="{{route('games.destroy',$game)}}" method="post" onsubmit="return confirmDelete()">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">刪除</button>
                </form>
            </div>
            @endcan
            @can('manager')
            <div class="d-flex justify-content-end">
                <a href="{{route('games.edit',['game'=>$game->id])}}" class="btn btn-outline-primary" style="margin-right:10px ">編輯</a>
                <form action="{{route('games.destroy',$game)}}" method="post" onsubmit="return confirmDelete()">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger" >刪除</button>
                </form>
            </div>
            @endcan
        </div>
        @endforeach
    </div>
</div>
<script>
    function confirmDelete() {
        return confirm("確定要刪除這個遊戲嗎？");
    }
</script>
@endsection

resources/views/games/index_all.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex">
        <h1 class="me-auto">遊戲總覽</h1>
        @can('admin')
        <a href="{{ route('games.create') }}" style="font-size: 30px">新增遊戲</a>
        @elsecan('manager')
        <a href="{{ route('games.create') }}" style="font-size: 30px">新增遊戲</a>
        @endcan
    </div>
    <select name="sort" id="sort" onchange="submitForm()">
        <option value="default" @if($sort === 'default') selected @endif>預設排序</option>
        <option value="time" @if($sort === 'time') selected @endif>按時間排序(最新)</option>
        <option value="timeReverse" @if($sort === 'timeReverse') selected @endif>按時間排序(最舊)</option>
        <option value="comments" @if($sort === 'comments') selected @endif>按留言數排序(由高到低)</option>
        <option value="commentsReverse" @if($sort === 'commentsReverse') selected @endif>按留言數排序(由低到高)</option>
        <option value="price" @if($sort === 'price') selected @endif>按價格排序(由高到低)</option>
        <option value="priceReverse" @if($sort === 'priceReverse') selected @endif>按價格排序(由低到高)</option>
    </select>
    <div class="list-group">
        @foreach($games as $game)
        <div class="qwer">
            <div class="list-group-item list-group-item-action m-1">
                <div class="d-flex justify-content-between ">
                    <!-- 標題 -->
                    <h2 class="font-bold text-lg" style="margin-bottom: 20px ">
                        <a href="{{route('games.show',$game)}}">{{$game->title}}</a>
                        <br>
                        <br>
                        <p style="font-size: 20px">#{{$game->tag}}</p>
                    </h2>
                    <!-- 圖片 -->
                    <div class="justify-content-end">
                        <img src="{{ asset('storage/' . $game->image) }}"  style="width: 200px;" alt="遊戲圖片">
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <!-- 價格和發行 -->
                    <p class="" style="font-size: 20px">
                        價格:{{$game->price}}
                    </p>
                    <p class="d-none d-md-block" style="font-size: 20px">{{$game->created_at}} 由 {{$game->user->name}} 發行</p>
                </div>
            </div>

            @can('admin')
            <div class="d-flex justify-content-end">
                <a href="{{route('games.edit',['game'=>$game->id])}}" class="btn btn-outline-primary" style="margin-right:10px">編輯</a>
                <form action="{{route('games.destroy',$game)}}" method="post"  onsubmit="return confirmDelete()">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">刪除</button>
                </form>
            </div>
            @endcan
            @can('manager')
            <div class="d-flex justify-content-end">
                <a href="{{route('games.edit',['game'=>$game->id])}}" class="btn btn-outline-primary" style="margin-right:10px" >編輯</a>
                <form action="{{route('games.destroy',$game)}}" method="post" onsubmit="return confirmDelete()">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">刪除</button>
                </form>
            </div>
            @endcan
        </div>
        @endforeach
    </div>
    {{$games->links()}}
    </div>
</div>
<script>
    function submitForm() {
        // 獲取選擇的值
        const selectedValue = document.getElementById('sort').value;
        
        // 根據選擇的值進行相應的操作
        if (selectedValue === 'default') {
            // 如果選擇的是預設排序，則直接跳轉到 index 頁面
            window.location.href = "{{ route('all') }}";
        } else {
            // 否則根據選擇的值提交表單
            const form = document.createElement('form');
            form.method = 'GET';
            form.action = "{{ route('all') }}";

            const input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'sort';
            input.value = selectedValue;

            form.appendChild(input);
            document.body.appendChild(form);

            form.submit();
        }
    }
    function confirmDelete() {
        return confirm("確定要刪除這個遊戲嗎？");
    }
</script>
@endsection

resources/views/games/search.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex">
        <h1 class="me-auto">遊戲列表</h1>
    </div>
    <div class="list-group">
        @if($games->isEmpty())
            <p style="font-size: 100px">沒找到</p>
        @else
        @foreach($games as $game)
        <div class="qwer">
            <div class="list-group-item list-group-item-action m-1">
                <div class="d-flex justify-content-between ">
                    <!-- 標題 -->
                    <h2 class="font-bold text-lg" style="margin-bottom: 20px ">
                        <a href="{{route('games.show',$game)}}">{{$game->title}}</a>
                        <br>
                        <br>
                        <p style="font-size: 20px">#{{$game->tag}}</p>
                    </h2>
                    <!-- 圖片 -->
                    <div class="justify-content-end">
                        <img src="{{ asset('storage/' . $game->image) }}"  style="width: 200px;" alt="遊戲圖片">
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <!-- 價格和發行 -->
                    <p class="" style="font-size: 20px">
                        價格:{{$game->price}}
                    </p>
                    <p class="d-none d-md-block" style="font-size: 20px">{{$game->created_at}} 由 {{$game->user->name}} 發行</p>
                </div>
            </div>
            @can('admin')
            <div class="d-flex justify-content-end">
                <a href="{{route('games.edit',['game'=>$game->id])}}" class="btn btn-outline-primary" style="margin-right:10px ">編輯</a>
                <form action="{{route('games.destroy',$game)}}" method="post" onsubmit="return confirmDelete()">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">刪除</button>
                </form>
            </div>
            @endcan
            @can('manager')
            <div class="d-flex justify-content-end">
                <a href="{{route('games.edit',['game'=>$game->id])}}" class="btn btn-outline-primary" style="margin-right:10px ">編輯</a>
                <form action="{{route('games.destroy',$game)}}" method="post" onsubmit="return confirmDelete()">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">刪除</button>
                </form>
            </div>
            @endcan
        @endforeach
        @endif
    </div>
    {{$games->links()}}
    </div>
    </div>
</div>
<script>
    function confirmDelete() {
        return confirm("確定要刪除這個遊戲嗎？");
    }
</script>
@endsection

resources/views/games/shoplist.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1 class="font-thin text-4xl">購物車</h1>
    @if ($games->isEmpty())
        <p style="font-size: 300px">空購物車請去消費</p>
    @else
    @if(auth()->check())
    <form action="{{ route('shoplist.clean') }}" method="post">
        @csrf
        <button type="submit" class="btn btn-primary">清空購物車</button>
    </form>
    @endif
    <div class="list-group">
        @foreach($games as $game)
        <div class="qwer">
            <div class="list-group-item list-group-item-action m-1">
                <div class="d-flex justify-content-between ">
                    <!-- 標題 -->
                    <h2 class="font-bold text-lg" style="margin-bottom: 20px ">
                        <a href="{{route('games.show',$game)}}">{{$game->title}}</a>
                        <br>
                        <br>
                        <p style="font-size: 20px">#{{$game->tag}}</p>
                    </h2>
                    <!-- 圖片 -->
                    <div class="justify-content-end">
                        <img src="{{ asset('storage/' . $game->image) }}"  style="width: 200px;" alt="遊戲圖片">
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <!-- 價格和發行 -->
                    <p class="" style="font-size: 20px">
                        價格:{{$game->price}}
                    </p>
                    <p class="d-none d-md-block" style="font-size: 20px">{{$game->created_at}} 由 {{$game->user->name}} 發行</p>
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <form action="{{ route('shoplist.destroy', $game->id) }}" method="post">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">刪除</button>
                </form>
            </div>
        </div>
        @endforeach
    </div>
    <div class="d-flex  justify-content-between">
        <div class="text-right mt-3">
            <p style="font-size: 20px">總金額: {{ $totalAmount }} 元</p>
        </div>    
        <div class="d-flex">
            <form action="{{ route('shoplist.buy') }}" method="POST">
                @csrf
                <button type="submit" class="btn btn-primary" style="font-size: 20px">購買</button>
            </form>
        </div>
    </div>
    @endif
</div>
@endsection